local modbase_desc_de = "Diese Mod fügt die EuroCity Wagenfamilie der SBB hinzu. Enthalten sind ein erste Klasse Wagen Apm, ein normaler zweite Klasse Wagen Bpm, ein zweite Klasse mit rollstuhlgeeignetem WC, ein zweite Klasse Velowagen und ein erste Klasse Panoramawagen. Diese jeweils in verschiedene Lackierungen über die Jahre hinweg.";
local modbase_desc_ch = "Lest das öberhoupt öber?";
local modbase_desc_fr = "Ce mod ajoute la famille de voitures EuroCity des CFF. Il s'agit d'une voiture de première classe Apm, d'une voiture normale de deuxième classe Bpm, d'une deuxième classe avec toilettes accessibles aux fauteuils roulants, d'une voiture de deuxième classe à vélos et d'une voiture panoramique de première classe. Chacun d'entre eux a été peint de différentes manières au fil des ans.";
local modbase_desc_en = "This mod adds the EuroCity coach family of the SBB. Included are a first class coach Apm, a normal second class coach Bpm, a second class coach Bpm with wheelchair accessible WC, a second class bicycle coach Bpm and a first class panoramic coach. Each in different liveries over the years. This mod adds the EuroCity coach family of the SBB. Included are a first class coach Apm, a normal second class coach Bpm, a second class coach Bpm with wheelchair accessible WC, a second class bicycle coach Bpm and a first class panoramic coach.";

local wagon_desc_de = "Mit einer Stückzahl von 237 abgelieferten Wagen machen die EC Wagen einen grossen Teil der Wagenflotte der SBB. Neben sämtlichen internationalen Wagengarnituren findet man die EC Wagen auch in allen EW IV Pendelzüge, wo immer ein EC Wagen mitfährt, damit eine rollstuhlgeeignete Toilette vorhanden ist.  ";
local wagon_desc_ch = "Lest das öberhoupt öber?";
local wagon_desc_fr = "Avec un nombre de 237 wagons délivrés, les voitures EC constituent une grande partie de la flotte de voitures des CFF. En plus de tous les trains internationaux, les voitures EC se trouvent également dans tous les trains-navettes EW IV, où une voiture EC voyage toujours avec le train afin qu'une toilette adaptée aux fauteuils roulants soit disponible.  ";
local wagon_desc_en = "With 237 coaches delivered, the EC coaches make up a large part of SBB's coach fleet. In addition to all international train sets, the EC coaches can also be found in all EW IV push-pull trains, where an EC coach always travels with the train so that a toilet suitable for wheelchairs is available.";


function data()
    return {
        de = {
            ["sbb_ec_mod_name"] = "SBB Eurocity Wagen",
            ["sbb_ec_mod_desc"] = modbase_desc_de,
            ["sbb_ec_set_name"] = "SBB Eurocity Wagen",
            ["sbb_ec_set_fake_name"] = "SBB Eurocity Fake Wagen",
            ["sbb_ec_routentafel_name"] = "Routentafel für EuroCity Wagen",
            ["sbb_ec_routentafel_tooltip"] = "Routentafel für die Wagen im EuroCity Design",
            ["sbb_cis_routentafel_name"] = "Routentafel für Cisalpino Wagen",
            ["sbb_cis_routentafel_tooltip"] = "Routentafel für die Wagen im Cisalpino Design",

            --Eurocity Design
            ["sbb_ec_eurocity_name"] = "Eurocity Design",
            ["sbb_ec_eurocity_tooltip"] = "Wagen in der ursprünglichen grauen Bemalung. (1989-2014)",
            ["sbb_ec_em08_name"] = "EM 08 Wagen",
            ["sbb_ec_em08_tooltip"] = "Wagen mit EM 08 Werbeaufkleber (2008)",
            ["sbb_ec_bpm_eurocity_normal_name"] = "SBB EC Bpm 61 - Eurocity Design",
            ["sbb_ec_bpm_eurocity_normal_desc"] = wagon_desc_de,
            ["sbb_ec_bpm_eurocity_behig_name"] = "SBB EC Bpm 61 mit Rollstuhlplätzen - Eurocity Design",
            ["sbb_ec_bpm_eurocity_behig_desc"] = wagon_desc_de,
            ["sbb_ec_bpm_eurocity_velo_name"] = "SBB EC Bpm 61 mit Veloplätzen - Eurocity Design",
            ["sbb_ec_bpm_eurocity_velo_desc"] = wagon_desc_de,
            ["sbb_ec_bpm_eurocity_em08_name"] = "SBB EC Bpm 61 - EM 08 Werbeaufkleber",
            ["sbb_ec_bpm_eurocity_em08_desc"] = wagon_desc_de,
            ["sbb_ec_apm_eurocity_name"] = "SBB EC Apm 61 - Eurocity Design",
            ["sbb_ec_apm_eurocity_desc"] = wagon_desc_de,
            ["sbb_ec_apm_pano_eurocity_name"] = "SBB Pano Apm 61 - Eurocity Design",
            ["sbb_ec_apm_pano_eurocity_desc"] = wagon_desc_de,

            -- Refit Design
            ["sbb_ec_refit_name"] = "IC Design",
            ["sbb_ec_refit_tooltip"] = "Wagen nach dem Refit in der neuen IC Bemalung. (2009-2023)",
            ["sbb_ec_bpm_refit_normal_name"] = "SBB EC Bpm 61 - IC Design",
            ["sbb_ec_bpm_refit_normal_desc"] = wagon_desc_de,
            ["sbb_ec_bpm_refit_behig_name"] = "SBB EC Bpm 61 mit Rollstuhlplätzen - IC Design",
            ["sbb_ec_bpm_refit_behig_desc"] = wagon_desc_de,
            ["sbb_ec_bpm_refit_velo_name"] = "SBB EC Bpm 61 mit Veloplätzen - IC Design",
            ["sbb_ec_bpm_refit_velo_desc"] = wagon_desc_de,
            ["sbb_ec_apm_refit_name"] = "SBB EC Apm 61 - IC Design",
            ["sbb_ec_apm_refit_desc"] = wagon_desc_de,
            ["sbb_ec_apm_pano_refit_name"] = "SBB Pano Apm 61 - IC Design",
            ["sbb_ec_apm_pano_refit_desc"] = wagon_desc_de,
            ["sbb_ec_apm_pano_gopex_name"] = "SBB Pano Apm 61 - Gotthard Panorma Express Design",
            ["sbb_ec_apm_pano_gopex_desc"] = wagon_desc_de,

            -- Behig Design
            ["sbb_ec_behig_name"] = "BehiG Design",
            ["sbb_ec_behig_tooltip"] = "Wagen in der neuen Behinderten gerechten Bemalung. (2020-)",
            ["sbb_ec_bpm_behig_normal_name"] = "SBB EC Bpm 61 - BehiG Design",
            ["sbb_ec_bpm_behig_normal_desc"] = wagon_desc_de,
            ["sbb_ec_bpm_behig_behig_name"] = "SBB EC Bpm 61 mit Rollstuhlplätzen - BehiG Design",
            ["sbb_ec_bpm_behig_behig_desc"] = wagon_desc_de,
            ["sbb_ec_bpm_behig_velo_name"] = "SBB EC Bpm 61 mit Veloplätzen - BehiG Design",
            ["sbb_ec_bpm_behig_velo_desc"] = wagon_desc_de,
            ["sbb_ec_apm_behig_name"] = "SBB EC Apm 61 - BehiG Design",
            ["sbb_ec_apm_behig_desc"] = wagon_desc_de,
            ["sbb_ec_apm_pano_behig_name"] = "SBB Pano Apm 61 - BehiG Design",
            ["sbb_ec_apm_pano_behig_desc"] = wagon_desc_de,

            --Cisalpino Design
            ["sbb_ec_cis_name"] = "Cisalpino Design",
            ["sbb_ec_cis_tooltip"] = "Wagen in der Cisalpino Bemalung. (2004-2009)",
            ["sbb_ec_apm_cis_name"] = "Cisalpino EC Apm 61",
            ["sbb_ec_apm_cis_desc"] = wagon_desc_de,
            ["sbb_ec_bpm_cis_name"] = "Cisalpino EC Bpm 61",
            ["sbb_ec_bpm_cis_desc"] = wagon_desc_de,

            --exCis Design
            ["sbb_ec_excis_name"] = "ehemalige Cisalpino Wagen mit SBB Logo",
            ["sbb_ec_excis_tooltip"] = "Wagen in der Cisalpino Bemalung mit SBB Logos. (2009-2014)",
            ["sbb_ec_apm_excis_name"] = "SBB EC Apm 61 - ehemaliges Cisalpino Design",
            ["sbb_ec_apm_excis_desc"] = wagon_desc_de,
            ["sbb_ec_bpm_excis_name"] = "SBB EC Bpm 61 - ehemaliges Cisalpino Design",
            ["sbb_ec_bpm_excis_desc"] = wagon_desc_de,

            --Common Parts
            ["hd_fake_name"] = "Fake Varianten",
            ["hd_fake_tooltip"] = "Sollen Fake Varianten dargestellt werden?",
            ["hd_hide"] = "Verstecken",
            ["hd_display"] = "Anzeigen",
            ["hd_1850"] = "Ab 1850",
            ["hd_infinite"] = "Unendlich",
            ["hd_random"] = "Zufall",
            ["hd_routentafel_empty"] = "Keine Routentafel",
            ["hd_startyear_tooltip"] = "Ab wann sollen die Wagen verfügbar sein?",
            ["hd_startyear_name"] = "Verfügbar ab?",
            ["hd_endyear_tooltip"] = "Bis wann sollen die Wagen verfügbar sein?",
            ["hd_endyear_name"] = "Verfügbar bis?",
            ["hd_display_bikes_name"] = "Velos darstellen",
            ["hd_display_bikes_tooltip"] = "Velos als Ladegut in den Wagen darstellen. (Fahrradständer und Mountainbike von Maverick2002 benötigt)",
            ["hd_set_desc"] = "Bitte nicht kaufen, dient nur als Gruppierung",
            ["hd_is_train_sound_mod_installed_name"] = "TRAIN SOUND MOD installiert",
            ["hd_is_train_sound_mod_installed_tooltip"] = "Ist der TRAIN SOUND MOD von Jay_Emanuel installiert?",
        },
        de_ch = {
            ["sbb_ec_mod_name"] = "SBB Eurocity Wäge",
            ["sbb_ec_mod_desc"] = modbase_desc_ch,
            ["sbb_ec_set_name"] = "SBB Eurocity Wäge",
            ["sbb_ec_set_fake_name"] = "SBB Eurocity Fake Wäge",
            ["sbb_ec_routentafel_name"] = "Routentafel für EuroCity Wagen",
            ["sbb_ec_routentafel_tooltip"] = "Routentafel für die Wagen im EuroCity Design",
            ["sbb_cis_routentafel_name"] = "Routentafel für Cisalpino Wagen",
            ["sbb_cis_routentafel_tooltip"] = "Routentafel für die Wagen im Cisalpino Design",

            --Eurocity Design
            ["sbb_ec_eurocity_name"] = "Eurocity Design",
            ["sbb_ec_eurocity_tooltip"] = "Wäge in der originale graue Bemalig. (1989-2014)",
            ["sbb_ec_em08_name"] = "EM 08 Wagen",
            ["sbb_ec_em08_tooltip"] = "Wage met EM 08 Werbeufchläber (2008)",
            ["sbb_ec_bpm_eurocity_normal_name"] = "SBB EC Bpm 61 - Eurocity Design",
            ["sbb_ec_bpm_eurocity_normal_desc"] = wagon_desc_ch,
            ["sbb_ec_bpm_eurocity_behig_name"] = "SBB EC Bpm 61 mit Rollstuhlplätzen - Eurocity Design",
            ["sbb_ec_bpm_eurocity_behig_desc"] = wagon_desc_ch,
            ["sbb_ec_bpm_eurocity_velo_name"] = "SBB EC Bpm 61 mit Veloplätzen - Eurocity Design",
            ["sbb_ec_bpm_eurocity_velo_desc"] = wagon_desc_ch,
            ["sbb_ec_bpm_eurocity_em08_name"] = "SBB EC Bpm 61 - EM 08 Werbeaufkleber",
            ["sbb_ec_bpm_eurocity_em08_desc"] = wagon_desc_ch,
            ["sbb_ec_apm_eurocity_name"] = "SBB EC Apm 61 - Eurocity Design",
            ["sbb_ec_apm_eurocity_desc"] = wagon_desc_ch,
            ["sbb_ec_apm_pano_eurocity_name"] = "SBB Pano Apm 61 - Eurocity Design",
            ["sbb_ec_apm_pano_eurocity_desc"] = wagon_desc_ch,

            -- Refit Design
            ["sbb_ec_refit_name"] = "IC Design",
            ["sbb_ec_refit_tooltip"] = "Wäge nochem Refit i de neue IC Bemalig. (2009-2023)",
            ["sbb_ec_bpm_refit_normal_name"] = "SBB EC Bpm 61 - IC Design",
            ["sbb_ec_bpm_refit_normal_desc"] = wagon_desc_ch,
            ["sbb_ec_bpm_refit_behig_name"] = "SBB EC Bpm 61 met Rollstuhlplätz - IC Design",
            ["sbb_ec_bpm_refit_behig_desc"] = wagon_desc_ch,
            ["sbb_ec_bpm_refit_velo_name"] = "SBB EC Bpm 61 met Veloplätz - IC Design",
            ["sbb_ec_bpm_refit_velo_desc"] = wagon_desc_ch,
            ["sbb_ec_apm_refit_name"] = "SBB EC Apm 61 - IC Design",
            ["sbb_ec_apm_refit_desc"] = wagon_desc_ch,
            ["sbb_ec_apm_pano_refit_name"] = "SBB Pano Apm 61 - IC Design",
            ["sbb_ec_apm_pano_refit_desc"] = wagon_desc_ch,
            ["sbb_ec_apm_pano_gopex_name"] = "SBB Pano Apm 61 - Gotthard Panorma Express Design",
            ["sbb_ec_apm_pano_gopex_desc"] = wagon_desc_ch,

            -- Behig Design
            ["sbb_ec_behig_name"] = "BehiG Design",
            ["sbb_ec_behig_tooltip"] = "Wäge i de neue Behinderte grechte Bemalig. (2020-)",
            ["sbb_ec_bpm_behig_normal_name"] = "SBB EC Bpm 61 - BehiG Design",
            ["sbb_ec_bpm_behig_normal_desc"] = wagon_desc_ch,
            ["sbb_ec_bpm_behig_behig_name"] = "SBB EC Bpm 61 mit Rollstuhlplätzen - BehiG Design",
            ["sbb_ec_bpm_behig_behig_desc"] = wagon_desc_ch,
            ["sbb_ec_bpm_behig_velo_name"] = "SBB EC Bpm 61 mit Veloplätzen - BehiG Design",
            ["sbb_ec_bpm_behig_velo_desc"] = wagon_desc_ch,
            ["sbb_ec_apm_behig_name"] = "SBB EC Apm 61 - BehiG Design",
            ["sbb_ec_apm_behig_desc"] = wagon_desc_ch,
            ["sbb_ec_apm_pano_behig_name"] = "SBB Pano Apm 61 - BehiG Design",
            ["sbb_ec_apm_pano_behig_desc"] = wagon_desc_ch,

            --Cisalpino Design
            ["sbb_ec_cis_name"] = "Cisalpino Design",
            ["sbb_ec_cis_tooltip"] = "Wäge i de Cisalpino Bemalig. (2004-2009)",
            ["sbb_ec_apm_cis_name"] = "Cisalpino Apm 61",
            ["sbb_ec_apm_cis_desc"] = wagon_desc_ch,
            ["sbb_ec_bpm_cis_name"] = "Cisalpino Bpm 61",
            ["sbb_ec_bpm_cis_desc"] = wagon_desc_ch,

            --exCis Design
            ["sbb_ec_excis_name"] = "ehemalige Cisalpino Wagen mit SBB Logo",
            ["sbb_ec_excis_tooltip"] = "Wäge i de Cisalpino Bemalig met SBB Logos. (2009-2014)",
            ["sbb_ec_apm_excis_name"] = "SBB EC Apm 61 - ehemoligs Cisalpino Design",
            ["sbb_ec_apm_excis_desc"] = wagon_desc_ch,
            ["sbb_ec_bpm_excis_name"] = "SBB EC Bpm 61 - ehemoligs Cisalpino Design",
            ["sbb_ec_bpm_excis_desc"] = wagon_desc_ch,

            --Common Parts
            ["hd_fake_name"] = "Fake Variante",
            ["hd_fake_tooltip"] = "Sölled Fake Varianten azeigt werde?",
            ["hd_random"] = "Zuefall",
            ["hd_routentafel_empty"] = "Kei Routentafele",
            ["hd_startyear_tooltip"] = "Ab wenn sölled d Wäge verfüegbar si?",
            ["hd_startyear_name"] = "Verfüegbar ab?",
            ["hd_endyear_tooltip"] = "Bes wenn sölled d Wäge verfüegbar si?",
            ["hd_endyear_name"] = "Verfüegbar bis?",
            ["hd_hide"] = "Verstecke",
            ["hd_display"] = "Anzeige",
            ["hd_1850"] = "Ab 1850",
            ["hd_infinite"] = "Unendlich",
            ["hd_display_bikes_name"] = "Velos azeige",
            ["hd_display_bikes_tooltip"] = "Velos als Ladegut in den Wagen darstellen. (Fahrradständer und Mountainbike vom Maverick2002 benötigt)",
            ["hd_set_desc"] = "Bitte ned choufe, das isch nomme för d Gruppierig.",
            ["hd_is_train_sound_mod_installed_name"] = "TRAIN SOUND MOD installiert",
            ["hd_is_train_sound_mod_installed_tooltip"] = "Isch de TRAIN SOUND MOD vom Jay_Emanuel installiert?",
        },
        fr = {
            ["sbb_ec_mod_name"] = "CFF Voitures EuroCity",
            ["sbb_ec_mod_desc"] = modbase_desc_fr,
            ["sbb_ec_set_name"] = "CFF Voitures EuroCity",
            ["sbb_ec_set_fake_name"] = "CFF Voitures EuroCity (Fake-variantes)",
            ["sbb_ec_routentafel_name"] = "Plaque d'itineraire pour les voitures EuroCity",
            ["sbb_ec_routentafel_tooltip"] = "Plaque d'itineraire pour les wagons dans le design d'EuroCity",
            ["sbb_cis_routentafel_name"] = "Plaque d'itineraire pour les voitures Cisalpino",
            ["sbb_cis_routentafel_tooltip"] = "Plaque d'itineraire pour les wagons au design Cisalpino",

            --Eurocity Design
            ["sbb_ec_eurocity_name"] = "Eurocity Design",
            ["sbb_ec_eurocity_tooltip"] = "Voiture avec la livrée grise originale. (1989-2014)",
            ["sbb_ec_em08_name"] = "Voiture euro 08",
            ["sbb_ec_em08_tooltip"] = "Voiture avec un adhésif publicitaire de l'Euro 08 (2008)",
            ["sbb_ec_bpm_eurocity_normal_name"] = "CFF EC Bpm 61 - Eurocity Design",
            ["sbb_ec_bpm_eurocity_normal_desc"] = wagon_desc_fr,
            ["sbb_ec_bpm_eurocity_behig_name"] = "CFF EC Bpm 61 avec des places pour les fauteuils roulants - Eurocity Design",
            ["sbb_ec_bpm_eurocity_behig_desc"] = wagon_desc_fr,
            ["sbb_ec_bpm_eurocity_velo_name"] = "CFF EC Bpm 61 avec des espaces pour vélos - Eurocity Design",
            ["sbb_ec_bpm_eurocity_velo_desc"] = wagon_desc_fr,
            ["sbb_ec_bpm_eurocity_em08_name"] = "CFF EC Bpm 61 - Euro 08 adhésifs publicitaires",
            ["sbb_ec_bpm_eurocity_em08_desc"] = wagon_desc_fr,
            ["sbb_ec_apm_eurocity_name"] = "CFF EC Apm 61 - Eurocity Design",
            ["sbb_ec_apm_eurocity_desc"] = wagon_desc_fr,
            ["sbb_ec_apm_pano_eurocity_name"] = "CFF Apm 61 panoramique - Eurocity Design",
            ["sbb_ec_apm_pano_eurocity_desc"] = wagon_desc_fr,

            -- Refit Design
            ["sbb_ec_refit_name"] = "IC Design",
            ["sbb_ec_refit_tooltip"] = "La voiture après le refit dans la nouvelle livrée IC. (2009-2023)",
            ["sbb_ec_bpm_refit_normal_name"] = "CFF EC Bpm 61 - IC Design",
            ["sbb_ec_bpm_refit_normal_desc"] = wagon_desc_fr,
            ["sbb_ec_bpm_refit_behig_name"] = "CFF EC Bpm 61 avec des places pour les fauteuils roulants - IC Design",
            ["sbb_ec_bpm_refit_behig_desc"] = wagon_desc_fr,
            ["sbb_ec_bpm_refit_velo_name"] = "CFF EC Bpm 61 avec des espaces pour vélos - IC Design",
            ["sbb_ec_bpm_refit_velo_desc"] = wagon_desc_fr,
            ["sbb_ec_apm_refit_name"] = "CFF EC Apm 61 - IC Design",
            ["sbb_ec_apm_refit_desc"] = wagon_desc_fr,
            ["sbb_ec_apm_pano_refit_name"] = "CFF Apm 61 panoramique - IC Design",
            ["sbb_ec_apm_pano_refit_desc"] = wagon_desc_fr,
            ["sbb_ec_apm_pano_gopex_name"] = "CFF Apm 61 panoramique - Gotthard Panorma Express Design",
            ["sbb_ec_apm_pano_gopex_desc"] = wagon_desc_fr,

            -- Behig Design
            ["sbb_ec_behig_name"] = "BehiG Design",
            ["sbb_ec_behig_tooltip"] = "Voiture dans la nouvelle livrée accessible aux handicapés. (2020-)",
            ["sbb_ec_bpm_behig_normal_name"] = "CFF EC Bpm 61 - BehiG Design",
            ["sbb_ec_bpm_behig_normal_desc"] = wagon_desc_fr,
            ["sbb_ec_bpm_behig_behig_name"] = "CFF EC Bpm 61 mit Rollstuhlplätzen - BehiG Design",
            ["sbb_ec_bpm_behig_behig_desc"] = wagon_desc_fr,
            ["sbb_ec_bpm_behig_velo_name"] = "CFF EC Bpm 61 avec des espaces pour vélos - BehiG Design",
            ["sbb_ec_bpm_behig_velo_desc"] = wagon_desc_fr,
            ["sbb_ec_apm_behig_name"] = "CFF EC Apm 61 - BehiG Design",
            ["sbb_ec_apm_behig_desc"] = wagon_desc_fr,
            ["sbb_ec_apm_pano_behig_name"] = "CFF Apm 61 panoramique - BehiG Design",
            ["sbb_ec_apm_pano_behig_desc"] = wagon_desc_fr,

            --Cisalpino Design
            ["sbb_ec_cis_name"] = "Cisalpino Design",
            ["sbb_ec_cis_tooltip"] = "Voitures dans la livrée Cisalpino. (2004-2009)",
            ["sbb_ec_apm_cis_name"] = "Cisalpino EC Apm 61",
            ["sbb_ec_apm_cis_desc"] = wagon_desc_fr,
            ["sbb_ec_bpm_cis_name"] = "Cisalpino EC Bpm 61",
            ["sbb_ec_bpm_cis_desc"] = wagon_desc_fr,

            --exCis Design
            ["sbb_ec_excis_name"] = "ex-wagons Cisalpino avec le logo de la CFF",
            ["sbb_ec_excis_tooltip"] = "Voitures avec la livrée Cisalpino et les logos de la CFF. (2009-2014)",
            ["sbb_ec_apm_excis_name"] = "CFF EC Apm 61 - former Cisalpino design",
            ["sbb_ec_apm_excis_desc"] = wagon_desc_fr,
            ["sbb_ec_bpm_excis_name"] = "CFF EC Bpm 61 - former Cisalpino design",
            ["sbb_ec_bpm_excis_desc"] = wagon_desc_fr,

            --Common Parts
            ["hd_fake_name"] = "Fake-variantes",
            ["hd_fake_tooltip"] = "Faut-il montrer les fake variantes?",
            ["hd_random"] = "Random",
            ["hd_routentafel_empty"] = "Pas de plaque d'itineraire",
            ["hd_display_bikes_name"] = "Montrer les vélos",
            ["hd_display_bikes_tooltip"] = "Afficher les vélos comme cargaison dans les wagons. . (Fahrradständer und Mountainbike requise par Maverick2002)",
            ["hd_set_desc"] = "Ce fichier est pour groupe, n'acheté pas svp.",
            ["hd_startyear_tooltip"] = "À partir de quand les voitures doivent être disponibles?",
            ["hd_startyear_name"] = "Disponible à partir de?",
            ["hd_endyear_tooltip"] = "Quand les voitures devraient-elles être disponibles?",
            ["hd_endyear_name"] = "Disponible jusqu'au?",
            ["hd_hide"] = "cacher",
            ["hd_display"] = "afficher",
            ["hd_1850"] = "à partir de 1850",
            ["hd_infinite"] = "pas d'année de fin",
            ["hd_is_train_sound_mod_installed_name"] = "TRAIN SOUND MOD installé",
            ["hd_is_train_sound_mod_installed_tooltip"] = "Le TRAIN SOUND MOD de Jay_Emanuel est-il installé ?",
        },
        en = {
            ["sbb_ec_mod_name"] = "SBB EuroCity coaches",
            ["sbb_ec_mod_desc"] = modbase_desc_en,
            ["sbb_ec_set_name"] = "SBB EuroCity coaches",
            ["sbb_ec_set_fake_name"] = "SBB EuroCity coaches (fake-variants)",
            ["sbb_ec_routentafel_name"] = "Destination boards for EuroCity coaches",
            ["sbb_ec_routentafel_tooltip"] = "Destination boards for the wagons in the EuroCity design",
            ["sbb_cis_routentafel_name"] = "Destination boards for Cisalpino coaches",
            ["sbb_cis_routentafel_tooltip"] = "Destination boards for the wagons in the Cisalpino design",

            --Eurocity Design
            ["sbb_ec_eurocity_name"] = "Eurocity Design",
            ["sbb_ec_eurocity_tooltip"] = "Coaches in the original grey livery. (1989-2014)",
            ["sbb_ec_em08_name"] = "UEFA Euro 08 coach",
            ["sbb_ec_em08_tooltip"] = "Coach with a UEFA Euro 08 advertising sticker (2008)",
            ["sbb_ec_bpm_eurocity_normal_name"] = "SBB EC Bpm 61 - Eurocity Design",
            ["sbb_ec_bpm_eurocity_normal_desc"] = wagon_desc_en,
            ["sbb_ec_bpm_eurocity_behig_name"] = "SBB EC Bpm 61 with wheelchair spaces - Eurocity Design",
            ["sbb_ec_bpm_eurocity_behig_desc"] = wagon_desc_en,
            ["sbb_ec_bpm_eurocity_velo_name"] = "SBB EC Bpm 61 with bicycle spaces - Eurocity Design",
            ["sbb_ec_bpm_eurocity_velo_desc"] = wagon_desc_en,
            ["sbb_ec_bpm_eurocity_em08_name"] = "SBB EC Bpm 61 - UEFA Euro 08 advertising sticker",
            ["sbb_ec_bpm_eurocity_em08_desc"] = wagon_desc_en,
            ["sbb_ec_apm_eurocity_name"] = "SBB EC Apm 61 - Eurocity Design",
            ["sbb_ec_apm_eurocity_desc"] = wagon_desc_en,
            ["sbb_ec_apm_pano_eurocity_name"] = "SBB Apm 61 panoramic - Eurocity Design",
            ["sbb_ec_apm_pano_eurocity_desc"] = wagon_desc_en,

            -- Refit Design
            ["sbb_ec_refit_name"] = "IC Design",
            ["sbb_ec_refit_tooltip"] = "Coaches after the refit in the new IC livery. (2009-2023)",
            ["sbb_ec_bpm_refit_normal_name"] = "SBB EC Bpm 61 - IC Design",
            ["sbb_ec_bpm_refit_normal_desc"] = wagon_desc_en,
            ["sbb_ec_bpm_refit_behig_name"] = "SBB EC Bpm 61 with wheelchair spaces - IC Design",
            ["sbb_ec_bpm_refit_behig_desc"] = wagon_desc_en,
            ["sbb_ec_bpm_refit_velo_name"] = "SBB EC Bpm 61 with bicycle spaces - IC Design",
            ["sbb_ec_bpm_refit_velo_desc"] = wagon_desc_en,
            ["sbb_ec_apm_refit_name"] = "SBB EC Apm 61 - IC Design",
            ["sbb_ec_apm_refit_desc"] = wagon_desc_en,
            ["sbb_ec_apm_pano_refit_name"] = "SBB Apm 61 panoramic - IC Design",
            ["sbb_ec_apm_pano_refit_desc"] = wagon_desc_en,
            ["sbb_ec_apm_pano_gopex_name"] = "SBB Apm 61 panoramic - Gotthard Panorma Express Design",
            ["sbb_ec_apm_pano_gopex_desc"] = wagon_desc_en,

            -- Behig Design
            ["sbb_ec_behig_name"] = "BehiG Design",
            ["sbb_ec_behig_tooltip"] = "Coaches in the new handicapped-friendly livery. (2020-)",
            ["sbb_ec_bpm_behig_normal_name"] = "SBB EC Bpm 61 - BehiG Design",
            ["sbb_ec_bpm_behig_normal_desc"] = wagon_desc_en,
            ["sbb_ec_bpm_behig_behig_name"] = "SBB EC Bpm 61 with wheelchair spaces - BehiG Design",
            ["sbb_ec_bpm_behig_behig_desc"] = wagon_desc_en,
            ["sbb_ec_bpm_behig_velo_name"] = "SBB EC Bpm 61 with bicycle spaces- BehiG Design",
            ["sbb_ec_bpm_behig_velo_desc"] = wagon_desc_en,
            ["sbb_ec_apm_behig_name"] = "SBB EC Apm 61 - BehiG Design",
            ["sbb_ec_apm_behig_desc"] = wagon_desc_en,
            ["sbb_ec_apm_pano_behig_name"] = "SBB Apm 61 panoramic - BehiG Design",
            ["sbb_ec_apm_pano_behig_desc"] = wagon_desc_en,

            --Cisalpino Design
            ["sbb_ec_cis_name"] = "Cisalpino Design",
            ["sbb_ec_cis_tooltip"] = "Coaches in the Cisalpino livery. (2004-2009)",
            ["sbb_ec_apm_cis_name"] = "Cisalpino EC Apm 61",
            ["sbb_ec_apm_cis_desc"] = wagon_desc_en,
            ["sbb_ec_bpm_cis_name"] = "Cisalpino EC Bpm 61",
            ["sbb_ec_bpm_cis_desc"] = wagon_desc_en,

            --exCis Design
            ["sbb_ec_excis_name"] = "former Cisalpino coaches with SBB logo",
            ["sbb_ec_excis_tooltip"] = "Coaches in Cisalpino livery with SBB logos. (2009-2014)",
            ["sbb_ec_apm_excis_name"] = "SBB EC Apm 61 - former Cisalpino design",
            ["sbb_ec_apm_excis_desc"] = wagon_desc_en,
            ["sbb_ec_bpm_excis_name"] = "SBB EC Bpm 61 - former Cisalpino design",
            ["sbb_ec_bpm_excis_desc"] = wagon_desc_en,

            --Common Parts
            ["hd_fake_name"] = "Fake variants",
            ["hd_fake_tooltip"] = "Should fake variants be displayed?",
            ["hd_random"] = "Random",
            ["hd_routentafel_empty"] = "No destination board",
            ["hd_display_bikes_name"] = "Display bicycles",
            ["hd_display_bikes_tooltip"] = "Display bicycles as cargo in the coach. (Fahrradständer und Mountainbike by Maverick2002 needed)",
            ["hd_set_desc"] = "This is only for the grouping of the engines, please don't buy it.",
            ["hd_startyear_tooltip"] = "From which date should the coaches be available?",
            ["hd_startyear_name"] = "Available from?",
            ["hd_endyear_tooltip"] = "Until which date should the engines be available?",
            ["hd_endyear_name"] = "Available until?",
            ["hd_hide"] = "Hide",
            ["hd_display"] = "Display",
            ["hd_1850"] = "from 1850",
            ["hd_infinite"] = "no endyear",
            ["hd_is_train_sound_mod_installed_name"] = "TRAIN SOUND MOD installed",
            ["hd_is_train_sound_mod_installed_tooltip"] = "Is the TRAIN SOUND MOD by Jay_Emanuel installed?",
        },
    }
end
